name: View Root Directory

on: [push]

jobs:
  list-root-directory:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List root directory on macOS/Linux
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          ls -la /
        shell: bash

      - name: List root directory on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          dir
        shell: pwsh
