name: View Root Directory
on: [] # push
jobs:
  list-root-directory:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: test unix
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          pwd ; ls -lhA
        shell: bash

      - name: test win
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          pwd ; dir
        shell: pwsh
